[workspace]
resolver = "2"
members = [
    "client",
    "server",
    "shared",
]

[workspace.dependencies]
directories = "5.0"
log = "0.4"
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
simple_logger = "4.3"
tokio = { version = "1.37" }
